# Generated by Django 3.2.4 on 2023-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_filesadmin_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='adminupload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
